# Generated by Django 4.1.7 on 2023-05-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Статя', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Фото для статті', 'verbose_name_plural': 'Фото для статті'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.category', verbose_name='Категорія'),
        ),
    ]
